import { LexicalComposer } from "@lexical/react/LexicalComposer";
import { type NextPage } from "next";
import Head from "next/head";
import { editorConfig } from "~/components/editor/config";
import { Home } from "~/components/home";
import { api } from "~/utils/api";

const HomeScreen: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LexicalComposer initialConfig={editorConfig}>
        <Home />
      </LexicalComposer>
      <p className="text-2xl text-white">
        {hello.data ? hello.data.greeting : "Loading tRPC query..."}
      </p>
    </>
  );
};

export default HomeScreen;
